version: '3.5'
services:
  rabbitmq:
    container_name: rabbitmq
    build: .
    ports:
       - 4369:4369
       - 5671:5671
       - 5672:5672
       - 15671:15671
       - 15672:15672
       - 25672:25672
    restart: always
networks:
  default:
    name: exjex_network